// frontend/src/App.jsx
import React from 'react';
import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom';

import DashboardView from './views/DashboardView';
import BarbeiroView from './views/BarbeiroView';
import ClienteView from './views/ClienteView';
import ServicoView from './views/ServicoView';
import AgendamentoView from './views/AgendamentoView';

export default function App() {
  return (
    <Router>
      <div className="min-h-screen bg-slate-100/50">
        <nav className="bg-white border-b border-slate-200 p-4 shadow-sm">
          <div className="max-w-7xl mx-auto flex gap-4 text-sm font-medium text-slate-600">
            <Link to="/" className="hover:text-slate-900 transition-colors">Dashboard</Link>
            <Link to="/agendamentos" className="hover:text-slate-900 transition-colors">Agendamentos</Link>
            <Link to="/barbeiros" className="hover:text-slate-900 transition-colors">Barbeiros</Link>
            <Link to="/clientes" className="hover:text-slate-900 transition-colors">Clientes</Link>
            <Link to="/servicos" className="hover:text-slate-900 transition-colors">Serviços</Link>
          </div>
        </nav>

        <main className="max-w-7xl mx-auto p-6">
          <Routes>
            <Route path="/" element={<DashboardView />} />
            <Route path="/agendamentos" element={<AgendamentoView />} />
            <Route path="/barbeiros" element={<BarbeiroView />} />
            <Route path="/clientes" element={<ClienteView />} />
            <Route path="/servicos" element={<ServicoView />} />
          </Routes>
        </main>
      </div>
    </Router>
  );
}

// frontend/src/App.vue
<template>
  <div class="min-h-screen bg-slate-50 text-slate-800 antialiased font-sans p-6">

    <div class="max-w-4xl mx-auto bg-white rounded-xl shadow-sm border border-slate-100 p-6">

      <header class="flex flex-col sm:flex-row sm:items-center sm:justify-between border-b border-slate-100 pb-4 mb-6">
        <h1 class="text-xl font-bold tracking-tight text-slate-900">Barbearia do Zé</h1>

        <nav class="flex gap-2 mt-4 sm:mt-0 text-sm font-medium">
          <RouterLink to="/" class="nav-link">Início</RouterLink>
          <RouterLink to="/clientes" class="nav-link">Clientes</RouterLink>
          <RouterLink to="/barbeiros" class="nav-link">Barbeiros</RouterLink>
          <RouterLink to="/servicos" class="nav-link">Serviços</RouterLink>
          <RouterLink to="/agendamentos" class="nav-link">Agendamentos</RouterLink>
        </nav>
      </header>

      <main>
        <RouterView />
      </main>

    </div>
  </div>
</template>

<style scoped>
/* Importa as referências de utilitários para o escopo deste componente no v4 */
@import "tailwindcss";

/* Classes reutilizáveis do Tailwind para deixar os links bonitos */
.nav-link {
  @apply px-3 py-1.5 rounded-md text-slate-600 hover:text-slate-900 hover:bg-slate-100 transition-colors;
}

/* Estilo para quando a rota do menu estiver ativa */
.router-link-exact-active {
  @apply bg-slate-900 text-white hover:bg-slate-900 hover:text-white;
}
</style>
